version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: "sudo apt update"
      - run: "sudo apt install clang valgrind"
      - run: "git clone git@github.com:ThrowTheSwitch/Unity.git"
      - run:
          command: "gcc -c unity.c"
          working_directory: ./Unity/src/
      - run:
          command: "make exec_tests"
          environment:
            UNITY_DIR: ./Unity/
