version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: "sudo apt update"
      - run: "sudo apt install clang valgrind"
      - run: "make exec_tests"
